# This is a basic workflow to help you get started with Actions

name: Angular_CI_CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      # Runs a set of commands using the runners shell
      - name: npm install and build
        run: |
          # Iniciar resolución de dependencias
          sudo npm update -g npm
          sudo npm install -g @angular/cli
          sudo npm install
          sudo ng build --prod
          ls
          pwd
          cd dist
          pwd
          ls

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Build_Angular
          path: dist
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: Build_Angular
          path: dist
      
      # Runs a set of commands using the runners shell

      - name: npm install and build
        run: |
          pwd
          ls
          sudo apt-get update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu hirsute stable"
          sudo apt update
          sudo apt-cache search docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker
          

      - name: AWS ECR
        uses: kciter/aws-ecr-action@v3
        with:
          access_key_id: ASIASQCUKOWRJ6ACWQUW
          secret_access_key: cFNChld1yB+I9Fm2M1Z41M2yDVaXttI7W+i8b7Ha
          account_id: 171975538082
          repo: 171975538082.dkr.ecr.us-east-1.amazonaws.com/lazy_load
          region: us-east-1